/**
 * Unicode case test data
 */

/**
 * All lower case characters as in a single string.
 */
export const allLowerCaseCharacters = 
    // Basic Latin
    "abcdefghijklmnopqrstuvwxyz" +

    // Latin 1 Supplement
    "ßàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿ" +

    // Latin Extended A
    "āăąćĉċčďđēĕėęěĝğġģĥħĩīĭįıĳĵķĺļľŀłńņňŋōŏőœŕŗřśŝşšţťŧũūŭůűųŵŷźżž" +

    // Latin Extended B
    "ƀƃƅƈƌƒƙƚƞơƣƥƨƩƭưƴƶƹƽƿǆǉǌǎǐǒǔǖǘǚǜǟǡǣǥǧǩǫǭǯǳǵǹǻǽǿȁȃȅȇȉȋȍȏȑȓȕȗșțȝȟȣȥȧȩȫȭȯȱȳȼȿɀɂɇɉɋɍɏɓɔɖɗɘəɛɠɣɨɩɯɲʀʈʊʋʒ" +

    // IPA Extensions
    "ɐɑɒɥɪɱɵɽʉʌʔ" +

    // Greek and Coptic
    "άέήίαβγδεζηθικλμνξοπρστυφχψωϊϋόύώϣϥϧϩϫϭϯ" +

    // Cyrillic
    "абвгдежзийклмнопрстуфхцчшщъыьэюяёђѓєѕіїјљњћќўџѡѣѥѧѩѫѭѯѱѳѵѷѹѻѽѿҁґғҕҗҙқҝҟҡңҥҧҩҫҭүұҳҵҷҹһҽҿӂӄӈӌӑӓӕӗәӛӝӟӡӣӥӧөӫӯӱӳӵӹ" +

    // Armenian
    "աբգդեզէըթժիլխծկհձղճմյնշոչպջռսվտրցւփքօֆ" +

    // Georgian
    "აბგდევზთიკლმნოპჟრსტუფქღყშჩცძწჭხჯჰჱჲჳჴჵ" +
    
    // Latin Extended Additional
    "ḁḃḅḇḉḋḍḏḑḓḕḗḙḛḝḟḡḣḥḧḩḫḭḯḱḳḵḷḹḻḽḿṁṃṅṇṉṋṍṏṑṓṕṗṙṛṝṟṡṣṥṧṩṫṭṯṱṳṵṷṹṻṽṿẁẃẅẇẉẋẍẏẑẓẕạảấầẩẫậắằẳẵặẹẻẽếềểễệỉịọỏốồổỗộớờởỡợụủứừửữựỳỵỷỹ" +

    // Greek Extended
    "ἀἁἂἃἄἅἆἇἐἑἒἓἔἕἠἡἢἣἤἥἦἧἰἱἲἳἴἵἶἷὀὁὂὃὄὅὑὓὕὗὠὡὢὣὤὥὦὧᾀᾁᾂᾃᾄᾅᾆᾇᾐᾑᾒᾓᾔᾕᾖᾗᾠᾡᾢᾣᾤᾥᾦᾧᾰᾱῐῑῠῡ" +

    // Enclosed Alphanumerics
    "ⓐⓑⓒⓓⓔⓕⓖⓗⓘⓙⓚⓛⓜⓝⓞⓟⓠⓡⓢⓣⓤⓥⓦⓧⓨⓩ" +

    // Halfwidth and Fullwidth Forms
    "ａｂｃｄｅｆｇｈｉｊｋｌｍｎｏｐｑｒｓｔｕｖｗｘｙｚ";

/**
 * All upper case characters as in a single string.
 */
export const allUpperCaseCharacters =
    // Basic Latin
    "ABCDEFGHIJKLMNOPQRSTUVWXYZ" +

    // Latin 1 Supplement
    "ẞÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞŸ" +

    // Latin Extended A
    "ĀĂĄĆĈĊČĎĐĒĔĖĘĚĜĞĠĢĤĦĨĪĬĮİĲĴĶĹĻĽĿŁŃŅŇŊŌŎŐŒŔŖŘŚŜŞŠŢŤŦŨŪŬŮŰŲŴŶŹŻŽ" +

    // Latin Extended B
    "ɃƂƄƇƋƑƘȽȠƠƢƤƧʃƬƯƳƵƸƼǷǄǇǊǍǏǑǓǕǗǙǛǞǠǢǤǦǨǪǬǮǱǴǸǺǼǾȀȂȄȆȈȊȌȎȐȒȔȖȘȚȜȞȢȤȦȨȪȬȮȰȲȻⱾⱿɁɆɈɊɌɎƁƆƉƊƎƏƐƓƔƗƖƜƝƦƮƱƲƷ" +

    // IPA Extensions
    "ⱯⱭⱰꞍꞮⱮƟⱤɄɅˀ" + 

    // Greek and Coptic
    "ΆΈΉΊΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩΪΫΌΎΏϢϤϦϨϪϬϮ" +

    // Cyrillic
    "АБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯЁЂЃЄЅІЇЈЉЊЋЌЎЏѠѢѤѦѨѪѬѮѰѲѴѶѸѺѼѾҀҐҒҔҖҘҚҜҞҠҢҤҦҨҪҬҮҰҲҴҶҸҺҼҾӁӃӇӋӐӒӔӖӘӚӜӞӠӢӤӦӨӪӮӰӲӴӸ" +

    // Armenian
    "ԱԲԳԴԵԶԷԸԹԺԻԼԽԾԿՀՁՂՃՄՅՆՇՈՉՊՋՌՍՎՏՐՑՒՓՔՕՖ" +

    // Georgian
    "ႠႡႢႣႤႥႦႧႨႩႪႫႬႭႮႯႰႱႲႳႴႵႶႷႸႹႺႻႼႽႾႿჀჁჂჃჄჅ" +

    // Latin Extended Additional
    "ḀḂḄḆḈḊḌḎḐḒḔḖḘḚḜḞḠḢḤḦḨḪḬḮḰḲḴḶḸḺḼḾṀṂṄṆṈṊṌṎṐṒṔṖṘṚṜṞṠṢṤṦṨṪṬṮṰṲṴṶṸṺṼṾẀẂẄẆẈẊẌẎẐẒẔẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼẾỀỂỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪỬỮỰỲỴỶỸ" +

    // Greek Extended
    "ἈἉἊἋἌἍἎἏἘἙἚἛἜἝἨἩἪἫἬἭἮἯἸἹἺἻἼἽἾἿὈὉὊὋὌὍὙὛὝὟὨὩὪὫὬὭὮὯᾈᾉᾊᾋᾌᾍᾎᾏᾘᾙᾚᾛᾜᾝᾞᾟᾨᾩᾪᾫᾬᾭᾮᾯᾸᾹῘῙῨῩ" +

    // Enclosed Alphanumerics
    "ⒶⒷⒸⒹⒺⒻⒼⒽⒾⒿⓀⓁⓂⓃⓄⓅⓆⓇⓈⓉⓊⓋⓌⓍⓎⓏ" +

    // Halfwidth and Fullwidth Forms
    "ＡＢＣＤＥＦＧＨＩＪＫＬＭＮＯＰＱＲＳＴＵＶＷＸＹＺ";

/**
 * Array of lower case and upper case pairs.
 */
export const lowerUpperCasePairList = [
    // Basic Latin
    { lowerText: 'a', lowerChar: 0x0061, upperText: 'A', upperChar: 0x0041 },
    { lowerText: 'b', lowerChar: 0x0062, upperText: 'B', upperChar: 0x0042 },
    { lowerText: 'c', lowerChar: 0x0063, upperText: 'C', upperChar: 0x0043 },
    { lowerText: 'd', lowerChar: 0x0064, upperText: 'D', upperChar: 0x0044 },
    { lowerText: 'e', lowerChar: 0x0065, upperText: 'E', upperChar: 0x0045 },
    { lowerText: 'f', lowerChar: 0x0066, upperText: 'F', upperChar: 0x0046 },
    { lowerText: 'g', lowerChar: 0x0067, upperText: 'G', upperChar: 0x0047 },
    { lowerText: 'h', lowerChar: 0x0068, upperText: 'H', upperChar: 0x0048 },
    { lowerText: 'i', lowerChar: 0x0069, upperText: 'I', upperChar: 0x0049 },
    { lowerText: 'j', lowerChar: 0x006A, upperText: 'J', upperChar: 0x004A },
    { lowerText: 'k', lowerChar: 0x006B, upperText: 'K', upperChar: 0x004B },
    { lowerText: 'l', lowerChar: 0x006C, upperText: 'L', upperChar: 0x004C },
    { lowerText: 'm', lowerChar: 0x006D, upperText: 'M', upperChar: 0x004D },
    { lowerText: 'n', lowerChar: 0x006E, upperText: 'N', upperChar: 0x004E },
    { lowerText: 'o', lowerChar: 0x006F, upperText: 'O', upperChar: 0x004F },
    { lowerText: 'p', lowerChar: 0x0070, upperText: 'P', upperChar: 0x0050 },
    { lowerText: 'q', lowerChar: 0x0071, upperText: 'Q', upperChar: 0x0051 },
    { lowerText: 'r', lowerChar: 0x0072, upperText: 'R', upperChar: 0x0052 },
    { lowerText: 's', lowerChar: 0x0073, upperText: 'S', upperChar: 0x0053 },
    { lowerText: 't', lowerChar: 0x0074, upperText: 'T', upperChar: 0x0054 },
    { lowerText: 'u', lowerChar: 0x0075, upperText: 'U', upperChar: 0x0055 },
    { lowerText: 'v', lowerChar: 0x0076, upperText: 'V', upperChar: 0x0056 },
    { lowerText: 'w', lowerChar: 0x0077, upperText: 'W', upperChar: 0x0057 },
    { lowerText: 'x', lowerChar: 0x0078, upperText: 'X', upperChar: 0x0058 },
    { lowerText: 'y', lowerChar: 0x0079, upperText: 'Y', upperChar: 0x0059 },
    { lowerText: 'z', lowerChar: 0x007A, upperText: 'Z', upperChar: 0x005A },

    // Latin 1 Supplement
    { lowerText: 'ß', lowerChar: 0x00DF, upperText: 'ẞ', upperChar: 0x1E9E },
    { lowerText: 'à', lowerChar: 0x00E0, upperText: 'À', upperChar: 0x00C0 },
    { lowerText: 'á', lowerChar: 0x00E1, upperText: 'Á', upperChar: 0x00C1 },
    { lowerText: 'â', lowerChar: 0x00E2, upperText: 'Â', upperChar: 0x00C2 },
    { lowerText: 'ã', lowerChar: 0x00E3, upperText: 'Ã', upperChar: 0x00C3 },
    { lowerText: 'ä', lowerChar: 0x00E4, upperText: 'Ä', upperChar: 0x00C4 },
    { lowerText: 'å', lowerChar: 0x00E5, upperText: 'Å', upperChar: 0x00C5 },
    { lowerText: 'æ', lowerChar: 0x00E6, upperText: 'Æ', upperChar: 0x00C6 },
    { lowerText: 'ç', lowerChar: 0x00E7, upperText: 'Ç', upperChar: 0x00C7 },
    { lowerText: 'è', lowerChar: 0x00E8, upperText: 'È', upperChar: 0x00C8 },
    { lowerText: 'é', lowerChar: 0x00E9, upperText: 'É', upperChar: 0x00C9 },
    { lowerText: 'ê', lowerChar: 0x00EA, upperText: 'Ê', upperChar: 0x00CA },
    { lowerText: 'ë', lowerChar: 0x00EB, upperText: 'Ë', upperChar: 0x00CB },
    { lowerText: 'ì', lowerChar: 0x00EC, upperText: 'Ì', upperChar: 0x00CC },
    { lowerText: 'í', lowerChar: 0x00ED, upperText: 'Í', upperChar: 0x00CD },
    { lowerText: 'î', lowerChar: 0x00EE, upperText: 'Î', upperChar: 0x00CE },
    { lowerText: 'ï', lowerChar: 0x00EF, upperText: 'Ï', upperChar: 0x00CF },
    { lowerText: 'ð', lowerChar: 0x00F0, upperText: 'Ð', upperChar: 0x00D0 },
    { lowerText: 'ñ', lowerChar: 0x00F1, upperText: 'Ñ', upperChar: 0x00D1 },
    { lowerText: 'ò', lowerChar: 0x00F2, upperText: 'Ò', upperChar: 0x00D2 },
    { lowerText: 'ó', lowerChar: 0x00F3, upperText: 'Ó', upperChar: 0x00D3 },
    { lowerText: 'ô', lowerChar: 0x00F4, upperText: 'Ô', upperChar: 0x00D4 },
    { lowerText: 'õ', lowerChar: 0x00F5, upperText: 'Õ', upperChar: 0x00D5 },
    { lowerText: 'ö', lowerChar: 0x00F6, upperText: 'Ö', upperChar: 0x00D6 },
    { lowerText: 'ø', lowerChar: 0x00F8, upperText: 'Ø', upperChar: 0x00D8 },
    { lowerText: 'ù', lowerChar: 0x00F9, upperText: 'Ù', upperChar: 0x00D9 },
    { lowerText: 'ú', lowerChar: 0x00FA, upperText: 'Ú', upperChar: 0x00DA },
    { lowerText: 'û', lowerChar: 0x00FB, upperText: 'Û', upperChar: 0x00DB },
    { lowerText: 'ü', lowerChar: 0x00FC, upperText: 'Ü', upperChar: 0x00DC },
    { lowerText: 'ý', lowerChar: 0x00FD, upperText: 'Ý', upperChar: 0x00DD },
    { lowerText: 'þ', lowerChar: 0x00FE, upperText: 'Þ', upperChar: 0x00DE },
    { lowerText: 'ÿ', lowerChar: 0x00FF, upperText: 'Ÿ', upperChar: 0x0178 },
    
    // Latin Extended A
    { lowerText: 'ā', lowerChar: 0x0101, upperText: 'Ā', upperChar: 0x0100 },
    { lowerText: 'ă', lowerChar: 0x0103, upperText: 'Ă', upperChar: 0x0102 },
    { lowerText: 'ą', lowerChar: 0x0105, upperText: 'Ą', upperChar: 0x0104 },
    { lowerText: 'ć', lowerChar: 0x0107, upperText: 'Ć', upperChar: 0x0106 },
    { lowerText: 'ĉ', lowerChar: 0x0109, upperText: 'Ĉ', upperChar: 0x0108 },
    { lowerText: 'ċ', lowerChar: 0x010B, upperText: 'Ċ', upperChar: 0x010A },
    { lowerText: 'č', lowerChar: 0x010D, upperText: 'Č', upperChar: 0x010C },
    { lowerText: 'ď', lowerChar: 0x010F, upperText: 'Ď', upperChar: 0x010E },
    { lowerText: 'đ', lowerChar: 0x0111, upperText: 'Đ', upperChar: 0x0110 },
    { lowerText: 'ē', lowerChar: 0x0113, upperText: 'Ē', upperChar: 0x0112 },
    { lowerText: 'ĕ', lowerChar: 0x0115, upperText: 'Ĕ', upperChar: 0x0114 },
    { lowerText: 'ė', lowerChar: 0x0117, upperText: 'Ė', upperChar: 0x0116 },
    { lowerText: 'ę', lowerChar: 0x0119, upperText: 'Ę', upperChar: 0x0118 },
    { lowerText: 'ě', lowerChar: 0x011B, upperText: 'Ě', upperChar: 0x011A },
    { lowerText: 'ĝ', lowerChar: 0x011D, upperText: 'Ĝ', upperChar: 0x011C },
    { lowerText: 'ğ', lowerChar: 0x011F, upperText: 'Ğ', upperChar: 0x011E },
    { lowerText: 'ġ', lowerChar: 0x0121, upperText: 'Ġ', upperChar: 0x0120 },
    { lowerText: 'ģ', lowerChar: 0x0123, upperText: 'Ģ', upperChar: 0x0122 },
    { lowerText: 'ĥ', lowerChar: 0x0125, upperText: 'Ĥ', upperChar: 0x0124 },
    { lowerText: 'ħ', lowerChar: 0x0127, upperText: 'Ħ', upperChar: 0x0126 },
    { lowerText: 'ĩ', lowerChar: 0x0129, upperText: 'Ĩ', upperChar: 0x0128 },
    { lowerText: 'ī', lowerChar: 0x012B, upperText: 'Ī', upperChar: 0x012A },
    { lowerText: 'ĭ', lowerChar: 0x012D, upperText: 'Ĭ', upperChar: 0x012C },
    { lowerText: 'į', lowerChar: 0x012F, upperText: 'Į', upperChar: 0x012E },
    { lowerText: 'ı', lowerChar: 0x0131, upperText: 'İ', upperChar: 0x0130 },
    { lowerText: 'ĳ', lowerChar: 0x0133, upperText: 'Ĳ', upperChar: 0x0132 },
    { lowerText: 'ĵ', lowerChar: 0x0135, upperText: 'Ĵ', upperChar: 0x0134 },
    { lowerText: 'ķ', lowerChar: 0x0137, upperText: 'Ķ', upperChar: 0x0136 },
    { lowerText: 'ĺ', lowerChar: 0x013A, upperText: 'Ĺ', upperChar: 0x0139 },
    { lowerText: 'ļ', lowerChar: 0x013C, upperText: 'Ļ', upperChar: 0x013B },
    { lowerText: 'ľ', lowerChar: 0x013E, upperText: 'Ľ', upperChar: 0x013D },
    { lowerText: 'ŀ', lowerChar: 0x0140, upperText: 'Ŀ', upperChar: 0x013F },
    { lowerText: 'ł', lowerChar: 0x0142, upperText: 'Ł', upperChar: 0x0141 },
    { lowerText: 'ń', lowerChar: 0x0144, upperText: 'Ń', upperChar: 0x0143 },
    { lowerText: 'ņ', lowerChar: 0x0146, upperText: 'Ņ', upperChar: 0x0145 },
    { lowerText: 'ň', lowerChar: 0x0148, upperText: 'Ň', upperChar: 0x0147 },
    { lowerText: 'ŋ', lowerChar: 0x014B, upperText: 'Ŋ', upperChar: 0x014A },
    { lowerText: 'ō', lowerChar: 0x014D, upperText: 'Ō', upperChar: 0x014C },
    { lowerText: 'ŏ', lowerChar: 0x014F, upperText: 'Ŏ', upperChar: 0x014E },
    { lowerText: 'ő', lowerChar: 0x0151, upperText: 'Ő', upperChar: 0x0150 },
    { lowerText: 'œ', lowerChar: 0x0153, upperText: 'Œ', upperChar: 0x0152 },
    { lowerText: 'ŕ', lowerChar: 0x0155, upperText: 'Ŕ', upperChar: 0x0154 },
    { lowerText: 'ŗ', lowerChar: 0x0157, upperText: 'Ŗ', upperChar: 0x0156 },
    { lowerText: 'ř', lowerChar: 0x0159, upperText: 'Ř', upperChar: 0x0158 },
    { lowerText: 'ś', lowerChar: 0x015B, upperText: 'Ś', upperChar: 0x015A },
    { lowerText: 'ŝ', lowerChar: 0x015D, upperText: 'Ŝ', upperChar: 0x015C },
    { lowerText: 'ş', lowerChar: 0x015F, upperText: 'Ş', upperChar: 0x015E },
    { lowerText: 'š', lowerChar: 0x0161, upperText: 'Š', upperChar: 0x0160 },
    { lowerText: 'ţ', lowerChar: 0x0163, upperText: 'Ţ', upperChar: 0x0162 },
    { lowerText: 'ť', lowerChar: 0x0165, upperText: 'Ť', upperChar: 0x0164 },
    { lowerText: 'ŧ', lowerChar: 0x0167, upperText: 'Ŧ', upperChar: 0x0166 },
    { lowerText: 'ũ', lowerChar: 0x0169, upperText: 'Ũ', upperChar: 0x0168 },
    { lowerText: 'ū', lowerChar: 0x016B, upperText: 'Ū', upperChar: 0x016A },
    { lowerText: 'ŭ', lowerChar: 0x016D, upperText: 'Ŭ', upperChar: 0x016C },
    { lowerText: 'ů', lowerChar: 0x016F, upperText: 'Ů', upperChar: 0x016E },
    { lowerText: 'ű', lowerChar: 0x0171, upperText: 'Ű', upperChar: 0x0170 },
    { lowerText: 'ų', lowerChar: 0x0173, upperText: 'Ų', upperChar: 0x0172 },
    { lowerText: 'ŵ', lowerChar: 0x0175, upperText: 'Ŵ', upperChar: 0x0174 },
    { lowerText: 'ŷ', lowerChar: 0x0177, upperText: 'Ŷ', upperChar: 0x0176 },
    { lowerText: 'ź', lowerChar: 0x017A, upperText: 'Ź', upperChar: 0x0179 },
    { lowerText: 'ż', lowerChar: 0x017C, upperText: 'Ż', upperChar: 0x017B },
    { lowerText: 'ž', lowerChar: 0x017E, upperText: 'Ž', upperChar: 0x017D },
        
    // Latin Extended B
    { lowerText: 'ƀ', lowerChar: 0x0180, upperText: 'Ƀ', upperChar: 0x0243 },
    { lowerText: 'ƃ', lowerChar: 0x0183, upperText: 'Ƃ', upperChar: 0x0182 },
    { lowerText: 'ƅ', lowerChar: 0x0185, upperText: 'Ƅ', upperChar: 0x0184 },
    { lowerText: 'ƈ', lowerChar: 0x0188, upperText: 'Ƈ', upperChar: 0x0187 },
    { lowerText: 'ƌ', lowerChar: 0x018C, upperText: 'Ƌ', upperChar: 0x018B },
    { lowerText: 'ƒ', lowerChar: 0x0192, upperText: 'Ƒ', upperChar: 0x0191 },
    { lowerText: 'ƙ', lowerChar: 0x0199, upperText: 'Ƙ', upperChar: 0x0198 },
    { lowerText: 'ƚ', lowerChar: 0x019A, upperText: 'Ƚ', upperChar: 0x023D },
    { lowerText: 'ƞ', lowerChar: 0x019E, upperText: 'Ƞ', upperChar: 0x0220 },
    { lowerText: 'ơ', lowerChar: 0x01A1, upperText: 'Ơ', upperChar: 0x01A0 },
    { lowerText: 'ƣ', lowerChar: 0x01A3, upperText: 'Ƣ', upperChar: 0x01A2 },
    { lowerText: 'ƥ', lowerChar: 0x01A5, upperText: 'Ƥ', upperChar: 0x01A4 },
    { lowerText: 'ƨ', lowerChar: 0x01A8, upperText: 'Ƨ', upperChar: 0x01A7 },
    { lowerText: 'Ʃ', lowerChar: 0x01A9, upperText: 'ʃ', upperChar: 0x0283 },
    { lowerText: 'ƭ', lowerChar: 0x01AD, upperText: 'Ƭ', upperChar: 0x01AC },
    { lowerText: 'ư', lowerChar: 0x01B0, upperText: 'Ư', upperChar: 0x01AF },
    { lowerText: 'ƴ', lowerChar: 0x01B4, upperText: 'Ƴ', upperChar: 0x01B3 },
    { lowerText: 'ƶ', lowerChar: 0x01B6, upperText: 'Ƶ', upperChar: 0x01B5 },
    { lowerText: 'ƹ', lowerChar: 0x01B9, upperText: 'Ƹ', upperChar: 0x01B8 },
    { lowerText: 'ƽ', lowerChar: 0x01BD, upperText: 'Ƽ', upperChar: 0x01BC },
    { lowerText: 'ƿ', lowerChar: 0x01BF, upperText: 'Ƿ', upperChar: 0x01F7 },
    { lowerText: 'ǆ', lowerChar: 0x01C6, upperText: 'Ǆ', upperChar: 0x01C4 },
    { lowerText: 'ǉ', lowerChar: 0x01C9, upperText: 'Ǉ', upperChar: 0x01C7 },
    { lowerText: 'ǌ', lowerChar: 0x01CC, upperText: 'Ǌ', upperChar: 0x01CA },
    { lowerText: 'ǎ', lowerChar: 0x01CE, upperText: 'Ǎ', upperChar: 0x01CD },
    { lowerText: 'ǐ', lowerChar: 0x01D0, upperText: 'Ǐ', upperChar: 0x01CF },
    { lowerText: 'ǒ', lowerChar: 0x01D2, upperText: 'Ǒ', upperChar: 0x01D1 },
    { lowerText: 'ǔ', lowerChar: 0x01D4, upperText: 'Ǔ', upperChar: 0x01D3 },
    { lowerText: 'ǖ', lowerChar: 0x01D6, upperText: 'Ǖ', upperChar: 0x01D5 },
    { lowerText: 'ǘ', lowerChar: 0x01D8, upperText: 'Ǘ', upperChar: 0x01D7 },
    { lowerText: 'ǚ', lowerChar: 0x01DA, upperText: 'Ǚ', upperChar: 0x01D9 },
    { lowerText: 'ǜ', lowerChar: 0x01DC, upperText: 'Ǜ', upperChar: 0x01DB },
    { lowerText: 'ǟ', lowerChar: 0x01DF, upperText: 'Ǟ', upperChar: 0x01DE },
    { lowerText: 'ǡ', lowerChar: 0x01E1, upperText: 'Ǡ', upperChar: 0x01E0 },
    { lowerText: 'ǣ', lowerChar: 0x01E3, upperText: 'Ǣ', upperChar: 0x01E2 },
    { lowerText: 'ǥ', lowerChar: 0x01E5, upperText: 'Ǥ', upperChar: 0x01E4 },
    { lowerText: 'ǧ', lowerChar: 0x01E7, upperText: 'Ǧ', upperChar: 0x01E6 },
    { lowerText: 'ǩ', lowerChar: 0x01E9, upperText: 'Ǩ', upperChar: 0x01E8 },
    { lowerText: 'ǫ', lowerChar: 0x01EB, upperText: 'Ǫ', upperChar: 0x01EA },
    { lowerText: 'ǭ', lowerChar: 0x01ED, upperText: 'Ǭ', upperChar: 0x01EC },
    { lowerText: 'ǯ', lowerChar: 0x01EF, upperText: 'Ǯ', upperChar: 0x01EE },
    { lowerText: 'ǳ', lowerChar: 0x01F3, upperText: 'Ǳ', upperChar: 0x01F1 },
    { lowerText: 'ǵ', lowerChar: 0x01F5, upperText: 'Ǵ', upperChar: 0x01F4 },
    { lowerText: 'ǹ', lowerChar: 0x01F9, upperText: 'Ǹ', upperChar: 0x01F8 },
    { lowerText: 'ǻ', lowerChar: 0x01FB, upperText: 'Ǻ', upperChar: 0x01FA },
    { lowerText: 'ǽ', lowerChar: 0x01FD, upperText: 'Ǽ', upperChar: 0x01FC },
    { lowerText: 'ǿ', lowerChar: 0x01FF, upperText: 'Ǿ', upperChar: 0x01FE },
    { lowerText: 'ȁ', lowerChar: 0x0201, upperText: 'Ȁ', upperChar: 0x0200 },
    { lowerText: 'ȃ', lowerChar: 0x0203, upperText: 'Ȃ', upperChar: 0x0202 },
    { lowerText: 'ȅ', lowerChar: 0x0205, upperText: 'Ȅ', upperChar: 0x0204 },
    { lowerText: 'ȇ', lowerChar: 0x0207, upperText: 'Ȇ', upperChar: 0x0206 },
    { lowerText: 'ȉ', lowerChar: 0x0209, upperText: 'Ȉ', upperChar: 0x0208 },
    { lowerText: 'ȋ', lowerChar: 0x020B, upperText: 'Ȋ', upperChar: 0x020A },
    { lowerText: 'ȍ', lowerChar: 0x020D, upperText: 'Ȍ', upperChar: 0x020C },
    { lowerText: 'ȏ', lowerChar: 0x020F, upperText: 'Ȏ', upperChar: 0x020E },
    { lowerText: 'ȑ', lowerChar: 0x0211, upperText: 'Ȑ', upperChar: 0x0210 },
    { lowerText: 'ȓ', lowerChar: 0x0213, upperText: 'Ȓ', upperChar: 0x0212 },
    { lowerText: 'ȕ', lowerChar: 0x0215, upperText: 'Ȕ', upperChar: 0x0214 },
    { lowerText: 'ȗ', lowerChar: 0x0217, upperText: 'Ȗ', upperChar: 0x0216 },
    { lowerText: 'ș', lowerChar: 0x0219, upperText: 'Ș', upperChar: 0x0218 },
    { lowerText: 'ț', lowerChar: 0x021B, upperText: 'Ț', upperChar: 0x021A },
    { lowerText: 'ȝ', lowerChar: 0x021D, upperText: 'Ȝ', upperChar: 0x021C },
    { lowerText: 'ȟ', lowerChar: 0x021F, upperText: 'Ȟ', upperChar: 0x021E },
    { lowerText: 'ȣ', lowerChar: 0x0223, upperText: 'Ȣ', upperChar: 0x0222 },
    { lowerText: 'ȥ', lowerChar: 0x0225, upperText: 'Ȥ', upperChar: 0x0224 },
    { lowerText: 'ȧ', lowerChar: 0x0227, upperText: 'Ȧ', upperChar: 0x0226 },
    { lowerText: 'ȩ', lowerChar: 0x0229, upperText: 'Ȩ', upperChar: 0x0228 },
    { lowerText: 'ȫ', lowerChar: 0x022B, upperText: 'Ȫ', upperChar: 0x022A },
    { lowerText: 'ȭ', lowerChar: 0x022D, upperText: 'Ȭ', upperChar: 0x022C },
    { lowerText: 'ȯ', lowerChar: 0x022F, upperText: 'Ȯ', upperChar: 0x022E },
    { lowerText: 'ȱ', lowerChar: 0x0231, upperText: 'Ȱ', upperChar: 0x0230 },
    { lowerText: 'ȳ', lowerChar: 0x0233, upperText: 'Ȳ', upperChar: 0x0232 },
    { lowerText: 'ȼ', lowerChar: 0x023C, upperText: 'Ȼ', upperChar: 0x023B },
    { lowerText: 'ȿ', lowerChar: 0x023F, upperText: 'Ȿ', upperChar: 0x2C7E },
    { lowerText: 'ɀ', lowerChar: 0x0240, upperText: 'Ɀ', upperChar: 0x2C7F },
    { lowerText: 'ɂ', lowerChar: 0x0242, upperText: 'Ɂ', upperChar: 0x0241 },
    { lowerText: 'ɇ', lowerChar: 0x0247, upperText: 'Ɇ', upperChar: 0x0246 },
    { lowerText: 'ɉ', lowerChar: 0x0249, upperText: 'Ɉ', upperChar: 0x0248 },
    { lowerText: 'ɋ', lowerChar: 0x024B, upperText: 'Ɋ', upperChar: 0x024A },
    { lowerText: 'ɍ', lowerChar: 0x024D, upperText: 'Ɍ', upperChar: 0x024C },
    { lowerText: 'ɏ', lowerChar: 0x024F, upperText: 'Ɏ', upperChar: 0x024E },
    { lowerText: 'ɓ', lowerChar: 0x0253, upperText: 'Ɓ', upperChar: 0x0181 },
    { lowerText: 'ɔ', lowerChar: 0x0254, upperText: 'Ɔ', upperChar: 0x0186 },
    { lowerText: 'ɖ', lowerChar: 0x0256, upperText: 'Ɖ', upperChar: 0x0189 },
    { lowerText: 'ɗ', lowerChar: 0x0257, upperText: 'Ɗ', upperChar: 0x018A },
    { lowerText: 'ɘ', lowerChar: 0x0258, upperText: 'Ǝ', upperChar: 0x018E },
    { lowerText: 'ə', lowerChar: 0x0259, upperText: 'Ə', upperChar: 0x018F },
    { lowerText: 'ɛ', lowerChar: 0x025B, upperText: 'Ɛ', upperChar: 0x0190 },
    { lowerText: 'ɠ', lowerChar: 0x0260, upperText: 'Ɠ', upperChar: 0x0193 },
    { lowerText: 'ɣ', lowerChar: 0x0263, upperText: 'Ɣ', upperChar: 0x0194 },
    { lowerText: 'ɨ', lowerChar: 0x0268, upperText: 'Ɨ', upperChar: 0x0197 },
    { lowerText: 'ɩ', lowerChar: 0x0269, upperText: 'Ɩ', upperChar: 0x0196 },
    { lowerText: 'ɯ', lowerChar: 0x026F, upperText: 'Ɯ', upperChar: 0x019C },
    { lowerText: 'ɲ', lowerChar: 0x0272, upperText: 'Ɲ', upperChar: 0x019D },
    { lowerText: 'ʀ', lowerChar: 0x0280, upperText: 'Ʀ', upperChar: 0x01A6 },
    { lowerText: 'ʈ', lowerChar: 0x0288, upperText: 'Ʈ', upperChar: 0x01AE },
    { lowerText: 'ʊ', lowerChar: 0x028A, upperText: 'Ʊ', upperChar: 0x01B1 },
    { lowerText: 'ʋ', lowerChar: 0x028B, upperText: 'Ʋ', upperChar: 0x01B2 },
    { lowerText: 'ʒ', lowerChar: 0x0292, upperText: 'Ʒ', upperChar: 0x01B7 },
    
    // IPA Extensions
    { lowerText: 'ɐ', lowerChar: 0x0250, upperText: 'Ɐ', upperChar: 0x2C6F },
    { lowerText: 'ɑ', lowerChar: 0x0251, upperText: 'Ɑ', upperChar: 0x2C6D },
    { lowerText: 'ɒ', lowerChar: 0x0252, upperText: 'Ɒ', upperChar: 0x2C70 },
    { lowerText: 'ɥ', lowerChar: 0x0265, upperText: 'Ɥ', upperChar: 0xA78D },
    { lowerText: 'ɪ', lowerChar: 0x026A, upperText: 'Ɪ', upperChar: 0xA7AE },
    { lowerText: 'ɱ', lowerChar: 0x0271, upperText: 'Ɱ', upperChar: 0x2C6E },
    { lowerText: 'ɵ', lowerChar: 0x0275, upperText: 'Ɵ', upperChar: 0x019F },
    { lowerText: 'ɽ', lowerChar: 0x027D, upperText: 'Ɽ', upperChar: 0x2C64 },
    { lowerText: 'ʉ', lowerChar: 0x0289, upperText: 'Ʉ', upperChar: 0x0244 },
    { lowerText: 'ʌ', lowerChar: 0x028C, upperText: 'Ʌ', upperChar: 0x0245 },
    { lowerText: 'ʔ', lowerChar: 0x0294, upperText: 'ˀ', upperChar: 0x02C0 },

    // Greek and Coptic
    { lowerText: 'ά', lowerChar: 0x03AC, upperText: 'Ά', upperChar: 0x0386 },
    { lowerText: 'έ', lowerChar: 0x03AD, upperText: 'Έ', upperChar: 0x0388 },
    { lowerText: 'ή', lowerChar: 0x03AE, upperText: 'Ή', upperChar: 0x0389 },
    { lowerText: 'ί', lowerChar: 0x03AF, upperText: 'Ί', upperChar: 0x038A },
    { lowerText: 'α', lowerChar: 0x03B1, upperText: 'Α', upperChar: 0x0391 },
    { lowerText: 'β', lowerChar: 0x03B2, upperText: 'Β', upperChar: 0x0392 },
    { lowerText: 'γ', lowerChar: 0x03B3, upperText: 'Γ', upperChar: 0x0393 },
    { lowerText: 'δ', lowerChar: 0x03B4, upperText: 'Δ', upperChar: 0x0394 },
    { lowerText: 'ε', lowerChar: 0x03B5, upperText: 'Ε', upperChar: 0x0395 },
    { lowerText: 'ζ', lowerChar: 0x03B6, upperText: 'Ζ', upperChar: 0x0396 },
    { lowerText: 'η', lowerChar: 0x03B7, upperText: 'Η', upperChar: 0x0397 },
    { lowerText: 'θ', lowerChar: 0x03B8, upperText: 'Θ', upperChar: 0x0398 },
    { lowerText: 'ι', lowerChar: 0x03B9, upperText: 'Ι', upperChar: 0x0399 },
    { lowerText: 'κ', lowerChar: 0x03BA, upperText: 'Κ', upperChar: 0x039A },
    { lowerText: 'λ', lowerChar: 0x03BB, upperText: 'Λ', upperChar: 0x039B },
    { lowerText: 'μ', lowerChar: 0x03BC, upperText: 'Μ', upperChar: 0x039C },
    { lowerText: 'ν', lowerChar: 0x03BD, upperText: 'Ν', upperChar: 0x039D },
    { lowerText: 'ξ', lowerChar: 0x03BE, upperText: 'Ξ', upperChar: 0x039E },
    { lowerText: 'ο', lowerChar: 0x03BF, upperText: 'Ο', upperChar: 0x039F },
    { lowerText: 'π', lowerChar: 0x03C0, upperText: 'Π', upperChar: 0x03A0 },
    { lowerText: 'ρ', lowerChar: 0x03C1, upperText: 'Ρ', upperChar: 0x03A1 },
    { lowerText: 'σ', lowerChar: 0x03C3, upperText: 'Σ', upperChar: 0x03A3 },
    { lowerText: 'τ', lowerChar: 0x03C4, upperText: 'Τ', upperChar: 0x03A4 },
    { lowerText: 'υ', lowerChar: 0x03C5, upperText: 'Υ', upperChar: 0x03A5 },
    { lowerText: 'φ', lowerChar: 0x03C6, upperText: 'Φ', upperChar: 0x03A6 },
    { lowerText: 'χ', lowerChar: 0x03C7, upperText: 'Χ', upperChar: 0x03A7 },
    { lowerText: 'ψ', lowerChar: 0x03C8, upperText: 'Ψ', upperChar: 0x03A8 },
    { lowerText: 'ω', lowerChar: 0x03C9, upperText: 'Ω', upperChar: 0x03A9 },
    { lowerText: 'ϊ', lowerChar: 0x03CA, upperText: 'Ϊ', upperChar: 0x03AA },
    { lowerText: 'ϋ', lowerChar: 0x03CB, upperText: 'Ϋ', upperChar: 0x03AB },
    { lowerText: 'ό', lowerChar: 0x03CC, upperText: 'Ό', upperChar: 0x038C },
    { lowerText: 'ύ', lowerChar: 0x03CD, upperText: 'Ύ', upperChar: 0x038E },
    { lowerText: 'ώ', lowerChar: 0x03CE, upperText: 'Ώ', upperChar: 0x038F },
    { lowerText: 'ϣ', lowerChar: 0x03E3, upperText: 'Ϣ', upperChar: 0x03E2 },
    { lowerText: 'ϥ', lowerChar: 0x03E5, upperText: 'Ϥ', upperChar: 0x03E4 },
    { lowerText: 'ϧ', lowerChar: 0x03E7, upperText: 'Ϧ', upperChar: 0x03E6 },
    { lowerText: 'ϩ', lowerChar: 0x03E9, upperText: 'Ϩ', upperChar: 0x03E8 },
    { lowerText: 'ϫ', lowerChar: 0x03EB, upperText: 'Ϫ', upperChar: 0x03EA },
    { lowerText: 'ϭ', lowerChar: 0x03ED, upperText: 'Ϭ', upperChar: 0x03EC },
    { lowerText: 'ϯ', lowerChar: 0x03EF, upperText: 'Ϯ', upperChar: 0x03EE },
  
    // Cyrillic
    { lowerText: 'а', lowerChar: 0x0430, upperText: 'А', upperChar: 0x0410 },
    { lowerText: 'б', lowerChar: 0x0431, upperText: 'Б', upperChar: 0x0411 },
    { lowerText: 'в', lowerChar: 0x0432, upperText: 'В', upperChar: 0x0412 },
    { lowerText: 'г', lowerChar: 0x0433, upperText: 'Г', upperChar: 0x0413 },
    { lowerText: 'д', lowerChar: 0x0434, upperText: 'Д', upperChar: 0x0414 },
    { lowerText: 'е', lowerChar: 0x0435, upperText: 'Е', upperChar: 0x0415 },
    { lowerText: 'ж', lowerChar: 0x0436, upperText: 'Ж', upperChar: 0x0416 },
    { lowerText: 'з', lowerChar: 0x0437, upperText: 'З', upperChar: 0x0417 },
    { lowerText: 'и', lowerChar: 0x0438, upperText: 'И', upperChar: 0x0418 },
    { lowerText: 'й', lowerChar: 0x0439, upperText: 'Й', upperChar: 0x0419 },
    { lowerText: 'к', lowerChar: 0x043A, upperText: 'К', upperChar: 0x041A },
    { lowerText: 'л', lowerChar: 0x043B, upperText: 'Л', upperChar: 0x041B },
    { lowerText: 'м', lowerChar: 0x043C, upperText: 'М', upperChar: 0x041C },
    { lowerText: 'н', lowerChar: 0x043D, upperText: 'Н', upperChar: 0x041D },
    { lowerText: 'о', lowerChar: 0x043E, upperText: 'О', upperChar: 0x041E },
    { lowerText: 'п', lowerChar: 0x043F, upperText: 'П', upperChar: 0x041F },
    { lowerText: 'р', lowerChar: 0x0440, upperText: 'Р', upperChar: 0x0420 },
    { lowerText: 'с', lowerChar: 0x0441, upperText: 'С', upperChar: 0x0421 },
    { lowerText: 'т', lowerChar: 0x0442, upperText: 'Т', upperChar: 0x0422 },
    { lowerText: 'у', lowerChar: 0x0443, upperText: 'У', upperChar: 0x0423 },
    { lowerText: 'ф', lowerChar: 0x0444, upperText: 'Ф', upperChar: 0x0424 },
    { lowerText: 'х', lowerChar: 0x0445, upperText: 'Х', upperChar: 0x0425 },
    { lowerText: 'ц', lowerChar: 0x0446, upperText: 'Ц', upperChar: 0x0426 },
    { lowerText: 'ч', lowerChar: 0x0447, upperText: 'Ч', upperChar: 0x0427 },
    { lowerText: 'ш', lowerChar: 0x0448, upperText: 'Ш', upperChar: 0x0428 },
    { lowerText: 'щ', lowerChar: 0x0449, upperText: 'Щ', upperChar: 0x0429 },
    { lowerText: 'ъ', lowerChar: 0x044A, upperText: 'Ъ', upperChar: 0x042A },
    { lowerText: 'ы', lowerChar: 0x044B, upperText: 'Ы', upperChar: 0x042B },
    { lowerText: 'ь', lowerChar: 0x044C, upperText: 'Ь', upperChar: 0x042C },
    { lowerText: 'э', lowerChar: 0x044D, upperText: 'Э', upperChar: 0x042D },
    { lowerText: 'ю', lowerChar: 0x044E, upperText: 'Ю', upperChar: 0x042E },
    { lowerText: 'я', lowerChar: 0x044F, upperText: 'Я', upperChar: 0x042F },
    { lowerText: 'ё', lowerChar: 0x0451, upperText: 'Ё', upperChar: 0x0401 },
    { lowerText: 'ђ', lowerChar: 0x0452, upperText: 'Ђ', upperChar: 0x0402 },
    { lowerText: 'ѓ', lowerChar: 0x0453, upperText: 'Ѓ', upperChar: 0x0403 },
    { lowerText: 'є', lowerChar: 0x0454, upperText: 'Є', upperChar: 0x0404 },
    { lowerText: 'ѕ', lowerChar: 0x0455, upperText: 'Ѕ', upperChar: 0x0405 },
    { lowerText: 'і', lowerChar: 0x0456, upperText: 'І', upperChar: 0x0406 },
    { lowerText: 'ї', lowerChar: 0x0457, upperText: 'Ї', upperChar: 0x0407 },
    { lowerText: 'ј', lowerChar: 0x0458, upperText: 'Ј', upperChar: 0x0408 },
    { lowerText: 'љ', lowerChar: 0x0459, upperText: 'Љ', upperChar: 0x0409 },
    { lowerText: 'њ', lowerChar: 0x045A, upperText: 'Њ', upperChar: 0x040A },
    { lowerText: 'ћ', lowerChar: 0x045B, upperText: 'Ћ', upperChar: 0x040B },
    { lowerText: 'ќ', lowerChar: 0x045C, upperText: 'Ќ', upperChar: 0x040C },
    { lowerText: 'ў', lowerChar: 0x045E, upperText: 'Ў', upperChar: 0x040E },
    { lowerText: 'џ', lowerChar: 0x045F, upperText: 'Џ', upperChar: 0x040F },
    { lowerText: 'ѡ', lowerChar: 0x0461, upperText: 'Ѡ', upperChar: 0x0460 },
    { lowerText: 'ѣ', lowerChar: 0x0463, upperText: 'Ѣ', upperChar: 0x0462 },
    { lowerText: 'ѥ', lowerChar: 0x0465, upperText: 'Ѥ', upperChar: 0x0464 },
    { lowerText: 'ѧ', lowerChar: 0x0467, upperText: 'Ѧ', upperChar: 0x0466 },
    { lowerText: 'ѩ', lowerChar: 0x0469, upperText: 'Ѩ', upperChar: 0x0468 },
    { lowerText: 'ѫ', lowerChar: 0x046B, upperText: 'Ѫ', upperChar: 0x046A },
    { lowerText: 'ѭ', lowerChar: 0x046D, upperText: 'Ѭ', upperChar: 0x046C },
    { lowerText: 'ѯ', lowerChar: 0x046F, upperText: 'Ѯ', upperChar: 0x046E },
    { lowerText: 'ѱ', lowerChar: 0x0471, upperText: 'Ѱ', upperChar: 0x0470 },
    { lowerText: 'ѳ', lowerChar: 0x0473, upperText: 'Ѳ', upperChar: 0x0472 },
    { lowerText: 'ѵ', lowerChar: 0x0475, upperText: 'Ѵ', upperChar: 0x0474 },
    { lowerText: 'ѷ', lowerChar: 0x0477, upperText: 'Ѷ', upperChar: 0x0476 },
    { lowerText: 'ѹ', lowerChar: 0x0479, upperText: 'Ѹ', upperChar: 0x0478 },
    { lowerText: 'ѻ', lowerChar: 0x047B, upperText: 'Ѻ', upperChar: 0x047A },
    { lowerText: 'ѽ', lowerChar: 0x047D, upperText: 'Ѽ', upperChar: 0x047C },
    { lowerText: 'ѿ', lowerChar: 0x047F, upperText: 'Ѿ', upperChar: 0x047E },
    { lowerText: 'ҁ', lowerChar: 0x0481, upperText: 'Ҁ', upperChar: 0x0480 },
    { lowerText: 'ґ', lowerChar: 0x0491, upperText: 'Ґ', upperChar: 0x0490 },
    { lowerText: 'ғ', lowerChar: 0x0493, upperText: 'Ғ', upperChar: 0x0492 },
    { lowerText: 'ҕ', lowerChar: 0x0495, upperText: 'Ҕ', upperChar: 0x0494 },
    { lowerText: 'җ', lowerChar: 0x0497, upperText: 'Җ', upperChar: 0x0496 },
    { lowerText: 'ҙ', lowerChar: 0x0499, upperText: 'Ҙ', upperChar: 0x0498 },
    { lowerText: 'қ', lowerChar: 0x049B, upperText: 'Қ', upperChar: 0x049A },
    { lowerText: 'ҝ', lowerChar: 0x049D, upperText: 'Ҝ', upperChar: 0x049C },
    { lowerText: 'ҟ', lowerChar: 0x049F, upperText: 'Ҟ', upperChar: 0x049E },
    { lowerText: 'ҡ', lowerChar: 0x04A1, upperText: 'Ҡ', upperChar: 0x04A0 },
    { lowerText: 'ң', lowerChar: 0x04A3, upperText: 'Ң', upperChar: 0x04A2 },
    { lowerText: 'ҥ', lowerChar: 0x04A5, upperText: 'Ҥ', upperChar: 0x04A4 },
    { lowerText: 'ҧ', lowerChar: 0x04A7, upperText: 'Ҧ', upperChar: 0x04A6 },
    { lowerText: 'ҩ', lowerChar: 0x04A9, upperText: 'Ҩ', upperChar: 0x04A8 },
    { lowerText: 'ҫ', lowerChar: 0x04AB, upperText: 'Ҫ', upperChar: 0x04AA },
    { lowerText: 'ҭ', lowerChar: 0x04AD, upperText: 'Ҭ', upperChar: 0x04AC },
    { lowerText: 'ү', lowerChar: 0x04AF, upperText: 'Ү', upperChar: 0x04AE },
    { lowerText: 'ұ', lowerChar: 0x04B1, upperText: 'Ұ', upperChar: 0x04B0 },
    { lowerText: 'ҳ', lowerChar: 0x04B3, upperText: 'Ҳ', upperChar: 0x04B2 },
    { lowerText: 'ҵ', lowerChar: 0x04B5, upperText: 'Ҵ', upperChar: 0x04B4 },
    { lowerText: 'ҷ', lowerChar: 0x04B7, upperText: 'Ҷ', upperChar: 0x04B6 },
    { lowerText: 'ҹ', lowerChar: 0x04B9, upperText: 'Ҹ', upperChar: 0x04B8 },
    { lowerText: 'һ', lowerChar: 0x04BB, upperText: 'Һ', upperChar: 0x04BA },
    { lowerText: 'ҽ', lowerChar: 0x04BD, upperText: 'Ҽ', upperChar: 0x04BC },
    { lowerText: 'ҿ', lowerChar: 0x04BF, upperText: 'Ҿ', upperChar: 0x04BE },
    { lowerText: 'ӂ', lowerChar: 0x04C2, upperText: 'Ӂ', upperChar: 0x04C1 },
    { lowerText: 'ӄ', lowerChar: 0x04C4, upperText: 'Ӄ', upperChar: 0x04C3 },
    { lowerText: 'ӈ', lowerChar: 0x04C8, upperText: 'Ӈ', upperChar: 0x04C7 },
    { lowerText: 'ӌ', lowerChar: 0x04CC, upperText: 'Ӌ', upperChar: 0x04CB },
    { lowerText: 'ӑ', lowerChar: 0x04D1, upperText: 'Ӑ', upperChar: 0x04D0 },
    { lowerText: 'ӓ', lowerChar: 0x04D3, upperText: 'Ӓ', upperChar: 0x04D2 },
    { lowerText: 'ӕ', lowerChar: 0x04D5, upperText: 'Ӕ', upperChar: 0x04D4 },
    { lowerText: 'ӗ', lowerChar: 0x04D7, upperText: 'Ӗ', upperChar: 0x04D6 },
    { lowerText: 'ә', lowerChar: 0x04D9, upperText: 'Ә', upperChar: 0x04D8 },
    { lowerText: 'ӛ', lowerChar: 0x04DB, upperText: 'Ӛ', upperChar: 0x04DA },
    { lowerText: 'ӝ', lowerChar: 0x04DD, upperText: 'Ӝ', upperChar: 0x04DC },
    { lowerText: 'ӟ', lowerChar: 0x04DF, upperText: 'Ӟ', upperChar: 0x04DE },
    { lowerText: 'ӡ', lowerChar: 0x04E1, upperText: 'Ӡ', upperChar: 0x04E0 },
    { lowerText: 'ӣ', lowerChar: 0x04E3, upperText: 'Ӣ', upperChar: 0x04E2 },
    { lowerText: 'ӥ', lowerChar: 0x04E5, upperText: 'Ӥ', upperChar: 0x04E4 },
    { lowerText: 'ӧ', lowerChar: 0x04E7, upperText: 'Ӧ', upperChar: 0x04E6 },
    { lowerText: 'ө', lowerChar: 0x04E9, upperText: 'Ө', upperChar: 0x04E8 },
    { lowerText: 'ӫ', lowerChar: 0x04EB, upperText: 'Ӫ', upperChar: 0x04EA },
    { lowerText: 'ӯ', lowerChar: 0x04EF, upperText: 'Ӯ', upperChar: 0x04EE },
    { lowerText: 'ӱ', lowerChar: 0x04F1, upperText: 'Ӱ', upperChar: 0x04F0 },
    { lowerText: 'ӳ', lowerChar: 0x04F3, upperText: 'Ӳ', upperChar: 0x04F2 },
    { lowerText: 'ӵ', lowerChar: 0x04F5, upperText: 'Ӵ', upperChar: 0x04F4 },
    { lowerText: 'ӹ', lowerChar: 0x04F9, upperText: 'Ӹ', upperChar: 0x04F8 },
  
    // Armenian
    { lowerText: 'ա', lowerChar: 0x0561, upperText: 'Ա', upperChar: 0x0531 },
    { lowerText: 'բ', lowerChar: 0x0562, upperText: 'Բ', upperChar: 0x0532 },
    { lowerText: 'գ', lowerChar: 0x0563, upperText: 'Գ', upperChar: 0x0533 },
    { lowerText: 'դ', lowerChar: 0x0564, upperText: 'Դ', upperChar: 0x0534 },
    { lowerText: 'ե', lowerChar: 0x0565, upperText: 'Ե', upperChar: 0x0535 },
    { lowerText: 'զ', lowerChar: 0x0566, upperText: 'Զ', upperChar: 0x0536 },
    { lowerText: 'է', lowerChar: 0x0567, upperText: 'Է', upperChar: 0x0537 },
    { lowerText: 'ը', lowerChar: 0x0568, upperText: 'Ը', upperChar: 0x0538 },
    { lowerText: 'թ', lowerChar: 0x0569, upperText: 'Թ', upperChar: 0x0539 },
    { lowerText: 'ժ', lowerChar: 0x056A, upperText: 'Ժ', upperChar: 0x053A },
    { lowerText: 'ի', lowerChar: 0x056B, upperText: 'Ի', upperChar: 0x053B },
    { lowerText: 'լ', lowerChar: 0x056C, upperText: 'Լ', upperChar: 0x053C },
    { lowerText: 'խ', lowerChar: 0x056D, upperText: 'Խ', upperChar: 0x053D },
    { lowerText: 'ծ', lowerChar: 0x056E, upperText: 'Ծ', upperChar: 0x053E },
    { lowerText: 'կ', lowerChar: 0x056F, upperText: 'Կ', upperChar: 0x053F },
    { lowerText: 'հ', lowerChar: 0x0570, upperText: 'Հ', upperChar: 0x0540 },
    { lowerText: 'ձ', lowerChar: 0x0571, upperText: 'Ձ', upperChar: 0x0541 },
    { lowerText: 'ղ', lowerChar: 0x0572, upperText: 'Ղ', upperChar: 0x0542 },
    { lowerText: 'ճ', lowerChar: 0x0573, upperText: 'Ճ', upperChar: 0x0543 },
    { lowerText: 'մ', lowerChar: 0x0574, upperText: 'Մ', upperChar: 0x0544 },
    { lowerText: 'յ', lowerChar: 0x0575, upperText: 'Յ', upperChar: 0x0545 },
    { lowerText: 'ն', lowerChar: 0x0576, upperText: 'Ն', upperChar: 0x0546 },
    { lowerText: 'շ', lowerChar: 0x0577, upperText: 'Շ', upperChar: 0x0547 },
    { lowerText: 'ո', lowerChar: 0x0578, upperText: 'Ո', upperChar: 0x0548 },
    { lowerText: 'չ', lowerChar: 0x0579, upperText: 'Չ', upperChar: 0x0549 },
    { lowerText: 'պ', lowerChar: 0x057A, upperText: 'Պ', upperChar: 0x054A },
    { lowerText: 'ջ', lowerChar: 0x057B, upperText: 'Ջ', upperChar: 0x054B },
    { lowerText: 'ռ', lowerChar: 0x057C, upperText: 'Ռ', upperChar: 0x054C },
    { lowerText: 'ս', lowerChar: 0x057D, upperText: 'Ս', upperChar: 0x054D },
    { lowerText: 'վ', lowerChar: 0x057E, upperText: 'Վ', upperChar: 0x054E },
    { lowerText: 'տ', lowerChar: 0x057F, upperText: 'Տ', upperChar: 0x054F },
    { lowerText: 'ր', lowerChar: 0x0580, upperText: 'Ր', upperChar: 0x0550 },
    { lowerText: 'ց', lowerChar: 0x0581, upperText: 'Ց', upperChar: 0x0551 },
    { lowerText: 'ւ', lowerChar: 0x0582, upperText: 'Ւ', upperChar: 0x0552 },
    { lowerText: 'փ', lowerChar: 0x0583, upperText: 'Փ', upperChar: 0x0553 },
    { lowerText: 'ք', lowerChar: 0x0584, upperText: 'Ք', upperChar: 0x0554 },
    { lowerText: 'օ', lowerChar: 0x0585, upperText: 'Օ', upperChar: 0x0555 },
    { lowerText: 'ֆ', lowerChar: 0x0586, upperText: 'Ֆ', upperChar: 0x0556 },
    
    // Georgian
    { lowerText: 'ა', lowerChar: 0x10D0, upperText: 'Ⴀ', upperChar: 0x10A0 },
    { lowerText: 'ბ', lowerChar: 0x10D1, upperText: 'Ⴁ', upperChar: 0x10A1 },
    { lowerText: 'გ', lowerChar: 0x10D2, upperText: 'Ⴂ', upperChar: 0x10A2 },
    { lowerText: 'დ', lowerChar: 0x10D3, upperText: 'Ⴃ', upperChar: 0x10A3 },
    { lowerText: 'ე', lowerChar: 0x10D4, upperText: 'Ⴄ', upperChar: 0x10A4 },
    { lowerText: 'ვ', lowerChar: 0x10D5, upperText: 'Ⴅ', upperChar: 0x10A5 },
    { lowerText: 'ზ', lowerChar: 0x10D6, upperText: 'Ⴆ', upperChar: 0x10A6 },
    { lowerText: 'თ', lowerChar: 0x10D7, upperText: 'Ⴇ', upperChar: 0x10A7 },
    { lowerText: 'ი', lowerChar: 0x10D8, upperText: 'Ⴈ', upperChar: 0x10A8 },
    { lowerText: 'კ', lowerChar: 0x10D9, upperText: 'Ⴉ', upperChar: 0x10A9 },
    { lowerText: 'ლ', lowerChar: 0x10DA, upperText: 'Ⴊ', upperChar: 0x10AA },
    { lowerText: 'მ', lowerChar: 0x10DB, upperText: 'Ⴋ', upperChar: 0x10AB },
    { lowerText: 'ნ', lowerChar: 0x10DC, upperText: 'Ⴌ', upperChar: 0x10AC },
    { lowerText: 'ო', lowerChar: 0x10DD, upperText: 'Ⴍ', upperChar: 0x10AD },
    { lowerText: 'პ', lowerChar: 0x10DE, upperText: 'Ⴎ', upperChar: 0x10AE },
    { lowerText: 'ჟ', lowerChar: 0x10DF, upperText: 'Ⴏ', upperChar: 0x10AF },
    { lowerText: 'რ', lowerChar: 0x10E0, upperText: 'Ⴐ', upperChar: 0x10B0 },
    { lowerText: 'ს', lowerChar: 0x10E1, upperText: 'Ⴑ', upperChar: 0x10B1 },
    { lowerText: 'ტ', lowerChar: 0x10E2, upperText: 'Ⴒ', upperChar: 0x10B2 },
    { lowerText: 'უ', lowerChar: 0x10E3, upperText: 'Ⴓ', upperChar: 0x10B3 },
    { lowerText: 'ფ', lowerChar: 0x10E4, upperText: 'Ⴔ', upperChar: 0x10B4 },
    { lowerText: 'ქ', lowerChar: 0x10E5, upperText: 'Ⴕ', upperChar: 0x10B5 },
    { lowerText: 'ღ', lowerChar: 0x10E6, upperText: 'Ⴖ', upperChar: 0x10B6 },
    { lowerText: 'ყ', lowerChar: 0x10E7, upperText: 'Ⴗ', upperChar: 0x10B7 },
    { lowerText: 'შ', lowerChar: 0x10E8, upperText: 'Ⴘ', upperChar: 0x10B8 },
    { lowerText: 'ჩ', lowerChar: 0x10E9, upperText: 'Ⴙ', upperChar: 0x10B9 },
    { lowerText: 'ც', lowerChar: 0x10EA, upperText: 'Ⴚ', upperChar: 0x10BA },
    { lowerText: 'ძ', lowerChar: 0x10EB, upperText: 'Ⴛ', upperChar: 0x10BB },
    { lowerText: 'წ', lowerChar: 0x10EC, upperText: 'Ⴜ', upperChar: 0x10BC },
    { lowerText: 'ჭ', lowerChar: 0x10ED, upperText: 'Ⴝ', upperChar: 0x10BD },
    { lowerText: 'ხ', lowerChar: 0x10EE, upperText: 'Ⴞ', upperChar: 0x10BE },
    { lowerText: 'ჯ', lowerChar: 0x10EF, upperText: 'Ⴟ', upperChar: 0x10BF },
    { lowerText: 'ჰ', lowerChar: 0x10F0, upperText: 'Ⴠ', upperChar: 0x10C0 },
    { lowerText: 'ჱ', lowerChar: 0x10F1, upperText: 'Ⴡ', upperChar: 0x10C1 },
    { lowerText: 'ჲ', lowerChar: 0x10F2, upperText: 'Ⴢ', upperChar: 0x10C2 },
    { lowerText: 'ჳ', lowerChar: 0x10F3, upperText: 'Ⴣ', upperChar: 0x10C3 },
    { lowerText: 'ჴ', lowerChar: 0x10F4, upperText: 'Ⴤ', upperChar: 0x10C4 },
    { lowerText: 'ჵ', lowerChar: 0x10F5, upperText: 'Ⴥ', upperChar: 0x10C5 },

    // Latin Extended Additional
    { lowerText: 'ḁ', lowerChar: 0x1E01, upperText: 'Ḁ', upperChar: 0x1E00 },
    { lowerText: 'ḃ', lowerChar: 0x1E03, upperText: 'Ḃ', upperChar: 0x1E02 },
    { lowerText: 'ḅ', lowerChar: 0x1E05, upperText: 'Ḅ', upperChar: 0x1E04 },
    { lowerText: 'ḇ', lowerChar: 0x1E07, upperText: 'Ḇ', upperChar: 0x1E06 },
    { lowerText: 'ḉ', lowerChar: 0x1E09, upperText: 'Ḉ', upperChar: 0x1E08 },
    { lowerText: 'ḋ', lowerChar: 0x1E0B, upperText: 'Ḋ', upperChar: 0x1E0A },
    { lowerText: 'ḍ', lowerChar: 0x1E0D, upperText: 'Ḍ', upperChar: 0x1E0C },
    { lowerText: 'ḏ', lowerChar: 0x1E0F, upperText: 'Ḏ', upperChar: 0x1E0E },
    { lowerText: 'ḑ', lowerChar: 0x1E11, upperText: 'Ḑ', upperChar: 0x1E10 },
    { lowerText: 'ḓ', lowerChar: 0x1E13, upperText: 'Ḓ', upperChar: 0x1E12 },
    { lowerText: 'ḕ', lowerChar: 0x1E15, upperText: 'Ḕ', upperChar: 0x1E14 },
    { lowerText: 'ḗ', lowerChar: 0x1E17, upperText: 'Ḗ', upperChar: 0x1E16 },
    { lowerText: 'ḙ', lowerChar: 0x1E19, upperText: 'Ḙ', upperChar: 0x1E18 },
    { lowerText: 'ḛ', lowerChar: 0x1E1B, upperText: 'Ḛ', upperChar: 0x1E1A },
    { lowerText: 'ḝ', lowerChar: 0x1E1D, upperText: 'Ḝ', upperChar: 0x1E1C },
    { lowerText: 'ḟ', lowerChar: 0x1E1F, upperText: 'Ḟ', upperChar: 0x1E1E },
    { lowerText: 'ḡ', lowerChar: 0x1E21, upperText: 'Ḡ', upperChar: 0x1E20 },
    { lowerText: 'ḣ', lowerChar: 0x1E23, upperText: 'Ḣ', upperChar: 0x1E22 },
    { lowerText: 'ḥ', lowerChar: 0x1E25, upperText: 'Ḥ', upperChar: 0x1E24 },
    { lowerText: 'ḧ', lowerChar: 0x1E27, upperText: 'Ḧ', upperChar: 0x1E26 },
    { lowerText: 'ḩ', lowerChar: 0x1E29, upperText: 'Ḩ', upperChar: 0x1E28 },
    { lowerText: 'ḫ', lowerChar: 0x1E2B, upperText: 'Ḫ', upperChar: 0x1E2A },
    { lowerText: 'ḭ', lowerChar: 0x1E2D, upperText: 'Ḭ', upperChar: 0x1E2C },
    { lowerText: 'ḯ', lowerChar: 0x1E2F, upperText: 'Ḯ', upperChar: 0x1E2E },
    { lowerText: 'ḱ', lowerChar: 0x1E31, upperText: 'Ḱ', upperChar: 0x1E30 },
    { lowerText: 'ḳ', lowerChar: 0x1E33, upperText: 'Ḳ', upperChar: 0x1E32 },
    { lowerText: 'ḵ', lowerChar: 0x1E35, upperText: 'Ḵ', upperChar: 0x1E34 },
    { lowerText: 'ḷ', lowerChar: 0x1E37, upperText: 'Ḷ', upperChar: 0x1E36 },
    { lowerText: 'ḹ', lowerChar: 0x1E39, upperText: 'Ḹ', upperChar: 0x1E38 },
    { lowerText: 'ḻ', lowerChar: 0x1E3B, upperText: 'Ḻ', upperChar: 0x1E3A },
    { lowerText: 'ḽ', lowerChar: 0x1E3D, upperText: 'Ḽ', upperChar: 0x1E3C },
    { lowerText: 'ḿ', lowerChar: 0x1E3F, upperText: 'Ḿ', upperChar: 0x1E3E },
    { lowerText: 'ṁ', lowerChar: 0x1E41, upperText: 'Ṁ', upperChar: 0x1E40 },
    { lowerText: 'ṃ', lowerChar: 0x1E43, upperText: 'Ṃ', upperChar: 0x1E42 },
    { lowerText: 'ṅ', lowerChar: 0x1E45, upperText: 'Ṅ', upperChar: 0x1E44 },
    { lowerText: 'ṇ', lowerChar: 0x1E47, upperText: 'Ṇ', upperChar: 0x1E46 },
    { lowerText: 'ṉ', lowerChar: 0x1E49, upperText: 'Ṉ', upperChar: 0x1E48 },
    { lowerText: 'ṋ', lowerChar: 0x1E4B, upperText: 'Ṋ', upperChar: 0x1E4A },
    { lowerText: 'ṍ', lowerChar: 0x1E4D, upperText: 'Ṍ', upperChar: 0x1E4C },
    { lowerText: 'ṏ', lowerChar: 0x1E4F, upperText: 'Ṏ', upperChar: 0x1E4E },
    { lowerText: 'ṑ', lowerChar: 0x1E51, upperText: 'Ṑ', upperChar: 0x1E50 },
    { lowerText: 'ṓ', lowerChar: 0x1E53, upperText: 'Ṓ', upperChar: 0x1E52 },
    { lowerText: 'ṕ', lowerChar: 0x1E55, upperText: 'Ṕ', upperChar: 0x1E54 },
    { lowerText: 'ṗ', lowerChar: 0x1E57, upperText: 'Ṗ', upperChar: 0x1E56 },
    { lowerText: 'ṙ', lowerChar: 0x1E59, upperText: 'Ṙ', upperChar: 0x1E58 },
    { lowerText: 'ṛ', lowerChar: 0x1E5B, upperText: 'Ṛ', upperChar: 0x1E5A },
    { lowerText: 'ṝ', lowerChar: 0x1E5D, upperText: 'Ṝ', upperChar: 0x1E5C },
    { lowerText: 'ṟ', lowerChar: 0x1E5F, upperText: 'Ṟ', upperChar: 0x1E5E },
    { lowerText: 'ṡ', lowerChar: 0x1E61, upperText: 'Ṡ', upperChar: 0x1E60 },
    { lowerText: 'ṣ', lowerChar: 0x1E63, upperText: 'Ṣ', upperChar: 0x1E62 },
    { lowerText: 'ṥ', lowerChar: 0x1E65, upperText: 'Ṥ', upperChar: 0x1E64 },
    { lowerText: 'ṧ', lowerChar: 0x1E67, upperText: 'Ṧ', upperChar: 0x1E66 },
    { lowerText: 'ṩ', lowerChar: 0x1E69, upperText: 'Ṩ', upperChar: 0x1E68 },
    { lowerText: 'ṫ', lowerChar: 0x1E6B, upperText: 'Ṫ', upperChar: 0x1E6A },
    { lowerText: 'ṭ', lowerChar: 0x1E6D, upperText: 'Ṭ', upperChar: 0x1E6C },
    { lowerText: 'ṯ', lowerChar: 0x1E6F, upperText: 'Ṯ', upperChar: 0x1E6E },
    { lowerText: 'ṱ', lowerChar: 0x1E71, upperText: 'Ṱ', upperChar: 0x1E70 },
    { lowerText: 'ṳ', lowerChar: 0x1E73, upperText: 'Ṳ', upperChar: 0x1E72 },
    { lowerText: 'ṵ', lowerChar: 0x1E75, upperText: 'Ṵ', upperChar: 0x1E74 },
    { lowerText: 'ṷ', lowerChar: 0x1E77, upperText: 'Ṷ', upperChar: 0x1E76 },
    { lowerText: 'ṹ', lowerChar: 0x1E79, upperText: 'Ṹ', upperChar: 0x1E78 },
    { lowerText: 'ṻ', lowerChar: 0x1E7B, upperText: 'Ṻ', upperChar: 0x1E7A },
    { lowerText: 'ṽ', lowerChar: 0x1E7D, upperText: 'Ṽ', upperChar: 0x1E7C },
    { lowerText: 'ṿ', lowerChar: 0x1E7F, upperText: 'Ṿ', upperChar: 0x1E7E },
    { lowerText: 'ẁ', lowerChar: 0x1E81, upperText: 'Ẁ', upperChar: 0x1E80 },
    { lowerText: 'ẃ', lowerChar: 0x1E83, upperText: 'Ẃ', upperChar: 0x1E82 },
    { lowerText: 'ẅ', lowerChar: 0x1E85, upperText: 'Ẅ', upperChar: 0x1E84 },
    { lowerText: 'ẇ', lowerChar: 0x1E87, upperText: 'Ẇ', upperChar: 0x1E86 },
    { lowerText: 'ẉ', lowerChar: 0x1E89, upperText: 'Ẉ', upperChar: 0x1E88 },
    { lowerText: 'ẋ', lowerChar: 0x1E8B, upperText: 'Ẋ', upperChar: 0x1E8A },
    { lowerText: 'ẍ', lowerChar: 0x1E8D, upperText: 'Ẍ', upperChar: 0x1E8C },
    { lowerText: 'ẏ', lowerChar: 0x1E8F, upperText: 'Ẏ', upperChar: 0x1E8E },
    { lowerText: 'ẑ', lowerChar: 0x1E91, upperText: 'Ẑ', upperChar: 0x1E90 },
    { lowerText: 'ẓ', lowerChar: 0x1E93, upperText: 'Ẓ', upperChar: 0x1E92 },
    { lowerText: 'ẕ', lowerChar: 0x1E95, upperText: 'Ẕ', upperChar: 0x1E94 },
    { lowerText: 'ạ', lowerChar: 0x1EA1, upperText: 'Ạ', upperChar: 0x1EA0 },
    { lowerText: 'ả', lowerChar: 0x1EA3, upperText: 'Ả', upperChar: 0x1EA2 },
    { lowerText: 'ấ', lowerChar: 0x1EA5, upperText: 'Ấ', upperChar: 0x1EA4 },
    { lowerText: 'ầ', lowerChar: 0x1EA7, upperText: 'Ầ', upperChar: 0x1EA6 },
    { lowerText: 'ẩ', lowerChar: 0x1EA9, upperText: 'Ẩ', upperChar: 0x1EA8 },
    { lowerText: 'ẫ', lowerChar: 0x1EAB, upperText: 'Ẫ', upperChar: 0x1EAA },
    { lowerText: 'ậ', lowerChar: 0x1EAD, upperText: 'Ậ', upperChar: 0x1EAC },
    { lowerText: 'ắ', lowerChar: 0x1EAF, upperText: 'Ắ', upperChar: 0x1EAE },
    { lowerText: 'ằ', lowerChar: 0x1EB1, upperText: 'Ằ', upperChar: 0x1EB0 },
    { lowerText: 'ẳ', lowerChar: 0x1EB3, upperText: 'Ẳ', upperChar: 0x1EB2 },
    { lowerText: 'ẵ', lowerChar: 0x1EB5, upperText: 'Ẵ', upperChar: 0x1EB4 },
    { lowerText: 'ặ', lowerChar: 0x1EB7, upperText: 'Ặ', upperChar: 0x1EB6 },
    { lowerText: 'ẹ', lowerChar: 0x1EB9, upperText: 'Ẹ', upperChar: 0x1EB8 },
    { lowerText: 'ẻ', lowerChar: 0x1EBB, upperText: 'Ẻ', upperChar: 0x1EBA },
    { lowerText: 'ẽ', lowerChar: 0x1EBD, upperText: 'Ẽ', upperChar: 0x1EBC },
    { lowerText: 'ế', lowerChar: 0x1EBF, upperText: 'Ế', upperChar: 0x1EBE },
    { lowerText: 'ề', lowerChar: 0x1EC1, upperText: 'Ề', upperChar: 0x1EC0 },
    { lowerText: 'ể', lowerChar: 0x1EC3, upperText: 'Ể', upperChar: 0x1EC2 },
    { lowerText: 'ễ', lowerChar: 0x1EC5, upperText: 'Ễ', upperChar: 0x1EC4 },
    { lowerText: 'ệ', lowerChar: 0x1EC7, upperText: 'Ệ', upperChar: 0x1EC6 },
    { lowerText: 'ỉ', lowerChar: 0x1EC9, upperText: 'Ỉ', upperChar: 0x1EC8 },
    { lowerText: 'ị', lowerChar: 0x1ECB, upperText: 'Ị', upperChar: 0x1ECA },
    { lowerText: 'ọ', lowerChar: 0x1ECD, upperText: 'Ọ', upperChar: 0x1ECC },
    { lowerText: 'ỏ', lowerChar: 0x1ECF, upperText: 'Ỏ', upperChar: 0x1ECE },
    { lowerText: 'ố', lowerChar: 0x1ED1, upperText: 'Ố', upperChar: 0x1ED0 },
    { lowerText: 'ồ', lowerChar: 0x1ED3, upperText: 'Ồ', upperChar: 0x1ED2 },
    { lowerText: 'ổ', lowerChar: 0x1ED5, upperText: 'Ổ', upperChar: 0x1ED4 },
    { lowerText: 'ỗ', lowerChar: 0x1ED7, upperText: 'Ỗ', upperChar: 0x1ED6 },
    { lowerText: 'ộ', lowerChar: 0x1ED9, upperText: 'Ộ', upperChar: 0x1ED8 },
    { lowerText: 'ớ', lowerChar: 0x1EDB, upperText: 'Ớ', upperChar: 0x1EDA },
    { lowerText: 'ờ', lowerChar: 0x1EDD, upperText: 'Ờ', upperChar: 0x1EDC },
    { lowerText: 'ở', lowerChar: 0x1EDF, upperText: 'Ở', upperChar: 0x1EDE },
    { lowerText: 'ỡ', lowerChar: 0x1EE1, upperText: 'Ỡ', upperChar: 0x1EE0 },
    { lowerText: 'ợ', lowerChar: 0x1EE3, upperText: 'Ợ', upperChar: 0x1EE2 },
    { lowerText: 'ụ', lowerChar: 0x1EE5, upperText: 'Ụ', upperChar: 0x1EE4 },
    { lowerText: 'ủ', lowerChar: 0x1EE7, upperText: 'Ủ', upperChar: 0x1EE6 },
    { lowerText: 'ứ', lowerChar: 0x1EE9, upperText: 'Ứ', upperChar: 0x1EE8 },
    { lowerText: 'ừ', lowerChar: 0x1EEB, upperText: 'Ừ', upperChar: 0x1EEA },
    { lowerText: 'ử', lowerChar: 0x1EED, upperText: 'Ử', upperChar: 0x1EEC },
    { lowerText: 'ữ', lowerChar: 0x1EEF, upperText: 'Ữ', upperChar: 0x1EEE },
    { lowerText: 'ự', lowerChar: 0x1EF1, upperText: 'Ự', upperChar: 0x1EF0 },
    { lowerText: 'ỳ', lowerChar: 0x1EF3, upperText: 'Ỳ', upperChar: 0x1EF2 },
    { lowerText: 'ỵ', lowerChar: 0x1EF5, upperText: 'Ỵ', upperChar: 0x1EF4 },
    { lowerText: 'ỷ', lowerChar: 0x1EF7, upperText: 'Ỷ', upperChar: 0x1EF6 },
    { lowerText: 'ỹ', lowerChar: 0x1EF9, upperText: 'Ỹ', upperChar: 0x1EF8 },
    
    // Greek Extended
    { lowerText: 'ἀ', lowerChar: 0x1F00, upperText: 'Ἀ', upperChar: 0x1F08 },
    { lowerText: 'ἁ', lowerChar: 0x1F01, upperText: 'Ἁ', upperChar: 0x1F09 },
    { lowerText: 'ἂ', lowerChar: 0x1F02, upperText: 'Ἂ', upperChar: 0x1F0A },
    { lowerText: 'ἃ', lowerChar: 0x1F03, upperText: 'Ἃ', upperChar: 0x1F0B },
    { lowerText: 'ἄ', lowerChar: 0x1F04, upperText: 'Ἄ', upperChar: 0x1F0C },
    { lowerText: 'ἅ', lowerChar: 0x1F05, upperText: 'Ἅ', upperChar: 0x1F0D },
    { lowerText: 'ἆ', lowerChar: 0x1F06, upperText: 'Ἆ', upperChar: 0x1F0E },
    { lowerText: 'ἇ', lowerChar: 0x1F07, upperText: 'Ἇ', upperChar: 0x1F0F },
    { lowerText: 'ἐ', lowerChar: 0x1F10, upperText: 'Ἐ', upperChar: 0x1F18 },
    { lowerText: 'ἑ', lowerChar: 0x1F11, upperText: 'Ἑ', upperChar: 0x1F19 },
    { lowerText: 'ἒ', lowerChar: 0x1F12, upperText: 'Ἒ', upperChar: 0x1F1A },
    { lowerText: 'ἓ', lowerChar: 0x1F13, upperText: 'Ἓ', upperChar: 0x1F1B },
    { lowerText: 'ἔ', lowerChar: 0x1F14, upperText: 'Ἔ', upperChar: 0x1F1C },
    { lowerText: 'ἕ', lowerChar: 0x1F15, upperText: 'Ἕ', upperChar: 0x1F1D },
    { lowerText: 'ἠ', lowerChar: 0x1F20, upperText: 'Ἠ', upperChar: 0x1F28 },
    { lowerText: 'ἡ', lowerChar: 0x1F21, upperText: 'Ἡ', upperChar: 0x1F29 },
    { lowerText: 'ἢ', lowerChar: 0x1F22, upperText: 'Ἢ', upperChar: 0x1F2A },
    { lowerText: 'ἣ', lowerChar: 0x1F23, upperText: 'Ἣ', upperChar: 0x1F2B },
    { lowerText: 'ἤ', lowerChar: 0x1F24, upperText: 'Ἤ', upperChar: 0x1F2C },
    { lowerText: 'ἥ', lowerChar: 0x1F25, upperText: 'Ἥ', upperChar: 0x1F2D },
    { lowerText: 'ἦ', lowerChar: 0x1F26, upperText: 'Ἦ', upperChar: 0x1F2E },
    { lowerText: 'ἧ', lowerChar: 0x1F27, upperText: 'Ἧ', upperChar: 0x1F2F },
    { lowerText: 'ἰ', lowerChar: 0x1F30, upperText: 'Ἰ', upperChar: 0x1F38 },
    { lowerText: 'ἱ', lowerChar: 0x1F31, upperText: 'Ἱ', upperChar: 0x1F39 },
    { lowerText: 'ἲ', lowerChar: 0x1F32, upperText: 'Ἲ', upperChar: 0x1F3A },
    { lowerText: 'ἳ', lowerChar: 0x1F33, upperText: 'Ἳ', upperChar: 0x1F3B },
    { lowerText: 'ἴ', lowerChar: 0x1F34, upperText: 'Ἴ', upperChar: 0x1F3C },
    { lowerText: 'ἵ', lowerChar: 0x1F35, upperText: 'Ἵ', upperChar: 0x1F3D },
    { lowerText: 'ἶ', lowerChar: 0x1F36, upperText: 'Ἶ', upperChar: 0x1F3E },
    { lowerText: 'ἷ', lowerChar: 0x1F37, upperText: 'Ἷ', upperChar: 0x1F3F },
    { lowerText: 'ὀ', lowerChar: 0x1F40, upperText: 'Ὀ', upperChar: 0x1F48 },
    { lowerText: 'ὁ', lowerChar: 0x1F41, upperText: 'Ὁ', upperChar: 0x1F49 },
    { lowerText: 'ὂ', lowerChar: 0x1F42, upperText: 'Ὂ', upperChar: 0x1F4A },
    { lowerText: 'ὃ', lowerChar: 0x1F43, upperText: 'Ὃ', upperChar: 0x1F4B },
    { lowerText: 'ὄ', lowerChar: 0x1F44, upperText: 'Ὄ', upperChar: 0x1F4C },
    { lowerText: 'ὅ', lowerChar: 0x1F45, upperText: 'Ὅ', upperChar: 0x1F4D },
    { lowerText: 'ὑ', lowerChar: 0x1F51, upperText: 'Ὑ', upperChar: 0x1F59 },
    { lowerText: 'ὓ', lowerChar: 0x1F53, upperText: 'Ὓ', upperChar: 0x1F5B },
    { lowerText: 'ὕ', lowerChar: 0x1F55, upperText: 'Ὕ', upperChar: 0x1F5D },
    { lowerText: 'ὗ', lowerChar: 0x1F57, upperText: 'Ὗ', upperChar: 0x1F5F },
    { lowerText: 'ὠ', lowerChar: 0x1F60, upperText: 'Ὠ', upperChar: 0x1F68 },
    { lowerText: 'ὡ', lowerChar: 0x1F61, upperText: 'Ὡ', upperChar: 0x1F69 },
    { lowerText: 'ὢ', lowerChar: 0x1F62, upperText: 'Ὢ', upperChar: 0x1F6A },
    { lowerText: 'ὣ', lowerChar: 0x1F63, upperText: 'Ὣ', upperChar: 0x1F6B },
    { lowerText: 'ὤ', lowerChar: 0x1F64, upperText: 'Ὤ', upperChar: 0x1F6C },
    { lowerText: 'ὥ', lowerChar: 0x1F65, upperText: 'Ὥ', upperChar: 0x1F6D },
    { lowerText: 'ὦ', lowerChar: 0x1F66, upperText: 'Ὦ', upperChar: 0x1F6E },
    { lowerText: 'ὧ', lowerChar: 0x1F67, upperText: 'Ὧ', upperChar: 0x1F6F },
    { lowerText: 'ᾀ', lowerChar: 0x1F80, upperText: 'ᾈ', upperChar: 0x1F88 },
    { lowerText: 'ᾁ', lowerChar: 0x1F81, upperText: 'ᾉ', upperChar: 0x1F89 },
    { lowerText: 'ᾂ', lowerChar: 0x1F82, upperText: 'ᾊ', upperChar: 0x1F8A },
    { lowerText: 'ᾃ', lowerChar: 0x1F83, upperText: 'ᾋ', upperChar: 0x1F8B },
    { lowerText: 'ᾄ', lowerChar: 0x1F84, upperText: 'ᾌ', upperChar: 0x1F8C },
    { lowerText: 'ᾅ', lowerChar: 0x1F85, upperText: 'ᾍ', upperChar: 0x1F8D },
    { lowerText: 'ᾆ', lowerChar: 0x1F86, upperText: 'ᾎ', upperChar: 0x1F8E },
    { lowerText: 'ᾇ', lowerChar: 0x1F87, upperText: 'ᾏ', upperChar: 0x1F8F },
    { lowerText: 'ᾐ', lowerChar: 0x1F90, upperText: 'ᾘ', upperChar: 0x1F98 },
    { lowerText: 'ᾑ', lowerChar: 0x1F91, upperText: 'ᾙ', upperChar: 0x1F99 },
    { lowerText: 'ᾒ', lowerChar: 0x1F92, upperText: 'ᾚ', upperChar: 0x1F9A },
    { lowerText: 'ᾓ', lowerChar: 0x1F93, upperText: 'ᾛ', upperChar: 0x1F9B },
    { lowerText: 'ᾔ', lowerChar: 0x1F94, upperText: 'ᾜ', upperChar: 0x1F9C },
    { lowerText: 'ᾕ', lowerChar: 0x1F95, upperText: 'ᾝ', upperChar: 0x1F9D },
    { lowerText: 'ᾖ', lowerChar: 0x1F96, upperText: 'ᾞ', upperChar: 0x1F9E },
    { lowerText: 'ᾗ', lowerChar: 0x1F97, upperText: 'ᾟ', upperChar: 0x1F9F },
    { lowerText: 'ᾠ', lowerChar: 0x1FA0, upperText: 'ᾨ', upperChar: 0x1FA8 },
    { lowerText: 'ᾡ', lowerChar: 0x1FA1, upperText: 'ᾩ', upperChar: 0x1FA9 },
    { lowerText: 'ᾢ', lowerChar: 0x1FA2, upperText: 'ᾪ', upperChar: 0x1FAA },
    { lowerText: 'ᾣ', lowerChar: 0x1FA3, upperText: 'ᾫ', upperChar: 0x1FAB },
    { lowerText: 'ᾤ', lowerChar: 0x1FA4, upperText: 'ᾬ', upperChar: 0x1FAC },
    { lowerText: 'ᾥ', lowerChar: 0x1FA5, upperText: 'ᾭ', upperChar: 0x1FAD },
    { lowerText: 'ᾦ', lowerChar: 0x1FA6, upperText: 'ᾮ', upperChar: 0x1FAE },
    { lowerText: 'ᾧ', lowerChar: 0x1FA7, upperText: 'ᾯ', upperChar: 0x1FAF },
    { lowerText: 'ᾰ', lowerChar: 0x1FB0, upperText: 'Ᾰ', upperChar: 0x1FB8 },
    { lowerText: 'ᾱ', lowerChar: 0x1FB1, upperText: 'Ᾱ', upperChar: 0x1FB9 },
    { lowerText: 'ῐ', lowerChar: 0x1FD0, upperText: 'Ῐ', upperChar: 0x1FD8 },
    { lowerText: 'ῑ', lowerChar: 0x1FD1, upperText: 'Ῑ', upperChar: 0x1FD9 },
    { lowerText: 'ῠ', lowerChar: 0x1FE0, upperText: 'Ῠ', upperChar: 0x1FE8 },
    { lowerText: 'ῡ', lowerChar: 0x1FE1, upperText: 'Ῡ', upperChar: 0x1FE9 },
  
    // Enclosed Alphanumerics
    { lowerText: 'ⓐ', lowerChar: 0x24D0, upperText: 'Ⓐ', upperChar: 0x24B6 },
    { lowerText: 'ⓑ', lowerChar: 0x24D1, upperText: 'Ⓑ', upperChar: 0x24B7 },
    { lowerText: 'ⓒ', lowerChar: 0x24D2, upperText: 'Ⓒ', upperChar: 0x24B8 },
    { lowerText: 'ⓓ', lowerChar: 0x24D3, upperText: 'Ⓓ', upperChar: 0x24B9 },
    { lowerText: 'ⓔ', lowerChar: 0x24D4, upperText: 'Ⓔ', upperChar: 0x24BA },
    { lowerText: 'ⓕ', lowerChar: 0x24D5, upperText: 'Ⓕ', upperChar: 0x24BB },
    { lowerText: 'ⓖ', lowerChar: 0x24D6, upperText: 'Ⓖ', upperChar: 0x24BC },
    { lowerText: 'ⓗ', lowerChar: 0x24D7, upperText: 'Ⓗ', upperChar: 0x24BD },
    { lowerText: 'ⓘ', lowerChar: 0x24D8, upperText: 'Ⓘ', upperChar: 0x24BE },
    { lowerText: 'ⓙ', lowerChar: 0x24D9, upperText: 'Ⓙ', upperChar: 0x24BF },
    { lowerText: 'ⓚ', lowerChar: 0x24DA, upperText: 'Ⓚ', upperChar: 0x24C0 },
    { lowerText: 'ⓛ', lowerChar: 0x24DB, upperText: 'Ⓛ', upperChar: 0x24C1 },
    { lowerText: 'ⓜ', lowerChar: 0x24DC, upperText: 'Ⓜ', upperChar: 0x24C2 },
    { lowerText: 'ⓝ', lowerChar: 0x24DD, upperText: 'Ⓝ', upperChar: 0x24C3 },
    { lowerText: 'ⓞ', lowerChar: 0x24DE, upperText: 'Ⓞ', upperChar: 0x24C4 },
    { lowerText: 'ⓟ', lowerChar: 0x24DF, upperText: 'Ⓟ', upperChar: 0x24C5 },
    { lowerText: 'ⓠ', lowerChar: 0x24E0, upperText: 'Ⓠ', upperChar: 0x24C6 },
    { lowerText: 'ⓡ', lowerChar: 0x24E1, upperText: 'Ⓡ', upperChar: 0x24C7 },
    { lowerText: 'ⓢ', lowerChar: 0x24E2, upperText: 'Ⓢ', upperChar: 0x24C8 },
    { lowerText: 'ⓣ', lowerChar: 0x24E3, upperText: 'Ⓣ', upperChar: 0x24C9 },
    { lowerText: 'ⓤ', lowerChar: 0x24E4, upperText: 'Ⓤ', upperChar: 0x24CA },
    { lowerText: 'ⓥ', lowerChar: 0x24E5, upperText: 'Ⓥ', upperChar: 0x24CB },
    { lowerText: 'ⓦ', lowerChar: 0x24E6, upperText: 'Ⓦ', upperChar: 0x24CC },
    { lowerText: 'ⓧ', lowerChar: 0x24E7, upperText: 'Ⓧ', upperChar: 0x24CD },
    { lowerText: 'ⓨ', lowerChar: 0x24E8, upperText: 'Ⓨ', upperChar: 0x24CE },
    { lowerText: 'ⓩ', lowerChar: 0x24E9, upperText: 'Ⓩ', upperChar: 0x24CF },
  
    // Halfwidth and Fullwidth Forms
    { lowerText: 'ａ', lowerChar: 0xFF41, upperText: 'Ａ', upperChar: 0xFF21 },
    { lowerText: 'ｂ', lowerChar: 0xFF42, upperText: 'Ｂ', upperChar: 0xFF22 },
    { lowerText: 'ｃ', lowerChar: 0xFF43, upperText: 'Ｃ', upperChar: 0xFF23 },
    { lowerText: 'ｄ', lowerChar: 0xFF44, upperText: 'Ｄ', upperChar: 0xFF24 },
    { lowerText: 'ｅ', lowerChar: 0xFF45, upperText: 'Ｅ', upperChar: 0xFF25 },
    { lowerText: 'ｆ', lowerChar: 0xFF46, upperText: 'Ｆ', upperChar: 0xFF26 },
    { lowerText: 'ｇ', lowerChar: 0xFF47, upperText: 'Ｇ', upperChar: 0xFF27 },
    { lowerText: 'ｈ', lowerChar: 0xFF48, upperText: 'Ｈ', upperChar: 0xFF28 },
    { lowerText: 'ｉ', lowerChar: 0xFF49, upperText: 'Ｉ', upperChar: 0xFF29 },
    { lowerText: 'ｊ', lowerChar: 0xFF4A, upperText: 'Ｊ', upperChar: 0xFF2A },
    { lowerText: 'ｋ', lowerChar: 0xFF4B, upperText: 'Ｋ', upperChar: 0xFF2B },
    { lowerText: 'ｌ', lowerChar: 0xFF4C, upperText: 'Ｌ', upperChar: 0xFF2C },
    { lowerText: 'ｍ', lowerChar: 0xFF4D, upperText: 'Ｍ', upperChar: 0xFF2D },
    { lowerText: 'ｎ', lowerChar: 0xFF4E, upperText: 'Ｎ', upperChar: 0xFF2E },
    { lowerText: 'ｏ', lowerChar: 0xFF4F, upperText: 'Ｏ', upperChar: 0xFF2F },
    { lowerText: 'ｐ', lowerChar: 0xFF50, upperText: 'Ｐ', upperChar: 0xFF30 },
    { lowerText: 'ｑ', lowerChar: 0xFF51, upperText: 'Ｑ', upperChar: 0xFF31 },
    { lowerText: 'ｒ', lowerChar: 0xFF52, upperText: 'Ｒ', upperChar: 0xFF32 },
    { lowerText: 'ｓ', lowerChar: 0xFF53, upperText: 'Ｓ', upperChar: 0xFF33 },
    { lowerText: 'ｔ', lowerChar: 0xFF54, upperText: 'Ｔ', upperChar: 0xFF34 },
    { lowerText: 'ｕ', lowerChar: 0xFF55, upperText: 'Ｕ', upperChar: 0xFF35 },
    { lowerText: 'ｖ', lowerChar: 0xFF56, upperText: 'Ｖ', upperChar: 0xFF36 },
    { lowerText: 'ｗ', lowerChar: 0xFF57, upperText: 'Ｗ', upperChar: 0xFF37 },
    { lowerText: 'ｘ', lowerChar: 0xFF58, upperText: 'Ｘ', upperChar: 0xFF38 },
    { lowerText: 'ｙ', lowerChar: 0xFF59, upperText: 'Ｙ', upperChar: 0xFF39 },
    { lowerText: 'ｚ', lowerChar: 0xFF5A, upperText: 'Ｚ', upperChar: 0xFF3A },    
];